version: 2
updates:
  # Обновление для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Обновление для npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Обновление для Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"