services:
  backend:
    build: ./backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - JULIA_PROJECT=@.
      - JULIA_DEBUG=all
    command: julia --project=. src/server.jl

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
