name: Docker Build
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t qdiagramlab-backend .

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t qdiagramlab-frontend .